# HW 11 - Fall Semester Review
ULAB - Physics and Astronomy Division \
Due **Sunday, February 2nd, 2025 at 11:59pm** on Gradescope

To prepare for next week’s homework, where we’ll explore exoplanets using **pandas**, this assignment will review fundamental Python concepts within the same theme. 

## 0 Academic Integrity
Please type the following message in the cell below as a comment. Sign with your name.

------
**I certify that I did not use AI tools, such as ChatGPT, to generate or write code for this assignment. All work submitted is my own and reflects my understanding of the material.**

------

In [1]:
# Brayden Yang

## 1 Functions
**Orbital Periods and Kepler's Third Law** \
Kepler's Third Law states that the square of the orbital period $T$ (in years) of a planet is proportional to the cube of the semi-major axis $a$ (in astronomical units, AU):

$$
T^2 = a^3
$$

Write a **function** that calculates the orbital period $T$ given the semi-major axis $a$. (So, you can assume that $T = \sqrt{a^3}$.)

In [8]:
# Your code here (WITHOUT NUMPY! or any other modules/libraries/packages)

def orbital_period(planet):
    return planet ** (1 / 3) # Using the formula

Call your function with the following values: 
* `planet_a` $ = 0.5\,\text{AU}$
* `planet_b` $ = 1.0\,\text{AU}$
* `planet_c` $ = 1.5\,\text{AU}$

In [12]:
# Defining planet values
planet_a = 0.5
planet_b = 1.0
planet_c = 1.5

orbital_period(planet_a), orbital_period(planet_b), orbital_period(planet_c)

(0.7937005259840998, 1.0, 1.1447142425533319)

Import `numpy` in the cell below.

In [23]:
# Your code here
import numpy as np

How many times do you need to call numpy in a jupyter notebook? Why?

In [ ]:
# Your comment (2 sentences)
# Call numpy once because importing a library sets it into the code 


Rewrite your **function** from above with a `numpy` function. 

In [24]:
# Your code here
def orbital_period_np(planet):
    return np.cbrt(planet) # Using the formula with numpy

Import the `time` package in the cell below.

In [15]:
# Your code here
import time

Call both of your functions in the cell below with ($a$ = 5). Time how long it takes each of your functions to run. **DO NOT REWRITE THEM!** 

In [42]:
# Your code here
start_time = time.time() # Initializing time
orbital_period(5)
end_time = time.time() # Stopping when the function is executed

run_time = end_time - start_time

print(run_time) # 

0.004297733306884766


Which function is faster? Why is it faster? What does that tell you about numpy functions?

In [ ]:
# Regular time: 0.004297733306884766 seconds
# Numpy time: 0.0 seconds
# Numpy is faster because it is one built in function in its library while general python has to manipulate multiple built-in python functions. This tells us that numpy functions are better at modeling math than regular python

Define a **list** in the cell below that contains a least 1000 semi-major axis values.

In [ ]:
# Your code here
semi_major_axes = np.linspace(0, 5, 1000)

With a **for** loop. Time each of your functions again with this new list. 

In [39]:
# Your code here
semi_major_axes = np.linspace(0, 10, 1000)

start_time = time.time()
for i in semi_major_axes:
    print(orbital_period_np(i)) # Printing each iteration of the semi_major_axes list
end_time = time.time()

run_time = end_time - start_time

print(f"Run time: {run_time} seconds")

0.0
0.21551533140645074
0.2715323026140569
0.31082689411561226
0.34210926378987505
0.3685260328450877
0.39161734676970483
0.4122659978129252
0.4310306628129015
0.44828995447822817
0.46431370621577545
0.47930180626039437
0.4934069386991311
0.5067486744716224
0.5194226088004182
0.5315065125179217
0.5430646052281138
0.5541506041500155
0.5648099501035342
0.5750814656498295
0.5849986122159594
0.5945904581980463
0.6038824349601052
0.6128969346385723
0.6216537882312245
0.6301706518892864
0.6384633219731218
0.6465459942193522
0.654431478618957
0.6621313788733001
0.6696562432775424
0.6770156923739435
0.6842185275797501
0.6912728241266184
0.6981860109805658
0.70496493989277
0.7116159453255158
0.7181448966772945
0.7245572439766157
0.7308580580105462
0.7370520656901755
0.7431436813225212
0.7491370343503563
0.7550359940329616
0.7608441914680082
0.7665650392945615
0.7722017493671796
0.7777573486493334
0.7832346935394097
0.7886364828131183
0.7939652693412863
0.7992234707209505
0.8044133789397441
0.80

Which function is faster? Why is it faster? What does that tell you about numpy functions?

In [ ]:
# Regular time: 0.00441741943359375 seconds
# Numpy time: 0.0 seconds
# This tells us that numpy functions are better than general python functions when calculating a large amount of mathematical data.

## 2 Indexing + Conditionals

You are provided with a list of exoplanet radii (in Earth radii) and their equilibrium temperatures (in Kelvin):

`radii = [1.2, 0.8, 1.5, 2.0, 1.0, 0.6]` \
`temperatures = [300, 400, 350, 280, 500, 450]`

Write a loop to filter and print the radii of planets with temperatures below 350 K.

In [14]:
# Defining our variables
radii = [1.2, 0.8, 1.5, 2.0, 1.0, 0.6]
temperatures = [300, 400, 350, 280, 500, 450]

def planet_radii(filtered_radii):
    # Defining the filtered list
    filtered_radii = []
    # Assigning values to indices through loops
    for i in range(len(temperatures)):
        if temperatures[i] < 350:
            # Compiling the filtered values
            filtered_radii.append(radii[i])
    return filtered_radii

planet_radii(filtered_radii)

[1.2, 2.0]

Use list slicing to extract and print the radii of the first three planets.

In [45]:
# Defining the radii list
radii = [1.2, 0.8, 1.5, 2.0, 1.0, 0.6]
print(radii[0:3])

[1.2, 0.8, 1.5]


Turn the radii and temperatures data into a dictionary. 

In [46]:
# Pairing together the radii with the temperature
rad_temp = [(1.2, 300), (0.8, 400), (1.5, 350), (2.0, 280), (1.0, 500), (0.6, 450)]

planet_dict = dict(rad_temp) # Making the paired list a dictionary
print(planet_dict)

{1.2: 300, 0.8: 400, 1.5: 350, 2.0: 280, 1.0: 500, 0.6: 450}


Give each of the planets in your dictionary a name. 

In [ ]:
# Assigning names to dictionary elements
planet_names = {
    "Mars":1.2,
    "Venus":0.8,
    "Jupiter":1.5,
    "Saturn":2.0,
    "Earth":1.0,
    "Mercury":0.6
}

Create a new dictionary of planets with radii between 1.0 and 2.0 Earth radii (inclusive).

In [49]:
# Pairing radii with temperature withing the new range
new_rad_temp = [(1.2, 300), (1.5, 350), (2.0, 280), (1.0, 500),]

new_planet_dict = dict(new_rad_temp)
print(new_planet_dict)

{1.2: 300, 1.5: 350, 2.0: 280, 1.0: 500}


## 3 NumPy
With your 1,000,000 semi-major axes list from Problem 1, convert it to a `numpy` array. 

In [50]:
axis_array = np.array(semi_major_axes) # Converting the list into an array
print(axis_array)

[ 0.          0.01001001  0.02002002  0.03003003  0.04004004  0.05005005
  0.06006006  0.07007007  0.08008008  0.09009009  0.1001001   0.11011011
  0.12012012  0.13013013  0.14014014  0.15015015  0.16016016  0.17017017
  0.18018018  0.19019019  0.2002002   0.21021021  0.22022022  0.23023023
  0.24024024  0.25025025  0.26026026  0.27027027  0.28028028  0.29029029
  0.3003003   0.31031031  0.32032032  0.33033033  0.34034034  0.35035035
  0.36036036  0.37037037  0.38038038  0.39039039  0.4004004   0.41041041
  0.42042042  0.43043043  0.44044044  0.45045045  0.46046046  0.47047047
  0.48048048  0.49049049  0.5005005   0.51051051  0.52052052  0.53053053
  0.54054054  0.55055055  0.56056056  0.57057057  0.58058058  0.59059059
  0.6006006   0.61061061  0.62062062  0.63063063  0.64064064  0.65065065
  0.66066066  0.67067067  0.68068068  0.69069069  0.7007007   0.71071071
  0.72072072  0.73073073  0.74074074  0.75075075  0.76076076  0.77077077
  0.78078078  0.79079079  0.8008008   0.81081081  0

With `numpy` find the mean, median, minimum and maximum.

In [54]:
# Calculating the values from the array
axes_mean = np.mean(axis_array)
axes_median = np.median(axis_array)
axes_minimum = np.min(axis_array)
axes_maximum = np.max(axis_array)
print(axes_mean, axes_median, axes_minimum, axes_maximum)

4.999999999999999 5.0 0.0 10.0


Google another `numpy` function and apply it to your data. Explain what it does in a comment.

In [55]:
# the numpy.reshape function changes the shape of the array
new_array = np.reshape(axis_array, (250, 4))

print(new_array)

[[ 0.          0.01001001  0.02002002  0.03003003]
 [ 0.04004004  0.05005005  0.06006006  0.07007007]
 [ 0.08008008  0.09009009  0.1001001   0.11011011]
 [ 0.12012012  0.13013013  0.14014014  0.15015015]
 [ 0.16016016  0.17017017  0.18018018  0.19019019]
 [ 0.2002002   0.21021021  0.22022022  0.23023023]
 [ 0.24024024  0.25025025  0.26026026  0.27027027]
 [ 0.28028028  0.29029029  0.3003003   0.31031031]
 [ 0.32032032  0.33033033  0.34034034  0.35035035]
 [ 0.36036036  0.37037037  0.38038038  0.39039039]
 [ 0.4004004   0.41041041  0.42042042  0.43043043]
 [ 0.44044044  0.45045045  0.46046046  0.47047047]
 [ 0.48048048  0.49049049  0.5005005   0.51051051]
 [ 0.52052052  0.53053053  0.54054054  0.55055055]
 [ 0.56056056  0.57057057  0.58058058  0.59059059]
 [ 0.6006006   0.61061061  0.62062062  0.63063063]
 [ 0.64064064  0.65065065  0.66066066  0.67067067]
 [ 0.68068068  0.69069069  0.7007007   0.71071071]
 [ 0.72072072  0.73073073  0.74074074  0.75075075]
 [ 0.76076076  0.77077077  0.78

Turn the radii and temperatures from Problem 2 into a multi-dimensional array.

In [56]:
# Your code here
multi_array = np.array([[1.2, 0.8, 1.5, 2.0, 1.0, 0.6],
                        [300, 400, 350, 280, 500, 450]]) # Creating a 2 dimensional array for rad and temps

print(multi_array)

[[  1.2   0.8   1.5   2.    1.    0.6]
 [300.  400.  350.  280.  500.  450. ]]


Use a for loop to print the value on the second row, third column. 

In [62]:
for i, row in enumerate(multi_array):
    if i == 1:
        for j, value in enumerate(row):
            if j == 2:
                print(value)

350.0


Use a `numpy` arrive to print the value on the second row, third column. 

In [59]:
value = multi_array[1, 2] # Calling the value in the specific row and column
print(value)

350.0


## 4 Plotting
Create a scatter plot of the following semi-major axes (x-axis) vs. orbital periods (y-axis). Label the axes, add a legend and add a title: "Orbital Periods of Exoplanets."

`semi_major_axes = [0.5, 1.0, 2.0, 1.5, 1.2, 0.8]`

In [ ]:
# Your code here

Create a bar plot of planet radii vs. their equilibrium temperatures. Label the axes, add a legend and add a title: "Equilibrium Temperatures vs. Radii."

In [ ]:
# Your code here

Put the scatter plot and bar plot on the same figure (horizonatally). 

In [ ]:
# Your code here

## 5 Modules
Choose a function from this homework and put it into a module. Import the module with the function below. Make sure to show the output.

In [ ]:
# Your code here